# Generated by Django 4.2.5 on 2023-10-02 14:32

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.utils.validate_phone]),
        ),
    ]
