# Generated by Django 4.2.5 on 2023-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_height',
            field=models.PositiveIntegerField(help_text='Высота изображения', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_width',
            field=models.PositiveIntegerField(help_text='Ширина изображения', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='profile/', width_field='image_widht'),
        ),
    ]
